test: Implement extension installation and basic extension handling test scenario
podman-desktop/extension-minikube pull request #209
Opened 2024-11-07 15:32 UTC by amisskii

### What does this PR do?

This PR adds a test scenario for the minikube extension

### What issues does this PR fix or reference?

https://github.com/containers/podman-desktop-extension-minikube/issues/137

### How to test this PR?

- Clone the podman-desktop repo
- cd to podman-desktop folder
- Execute pnpm install
- Execute pnpm build
- Set environment variable executing: export PODMAN_DESKTOP_ARGS="/path/to/podman-desktop"
- Clone the podman-desktop-extension-minikube repo
- cd  to  podman-desktop-extension-minikube folder
- Execute pnpm install
- Execute pnpm test:e2e

2024-11-08 08:22 UTC, ScrewTSW commented
A lot of your files are missing an empty line at the end of the file :D also, prcheck is failing

2024-11-15 13:55 UTC, odockal requested changes

2024-11-15 13:55 UTC, odockal commented on tests/playwright/src/spec/minikube-extension.spec.ts
> +import {
Missing copyright

2024-11-15 13:55 UTC, odockal commented on vitest.config.js
> +const excludeArray = [
copy right year 2023-2024

2024-11-15 13:55 UTC, odockal commented on tests/playwright/src/spec/minikube-extension.spec.ts
> +const skipExtensionInstallation = process.env.SKIP_EXTENSION_INSTALL ? process.env.SKIP_EXTENSION_INSTALL : false;
`= process.env.SKIP_EXTENSION_INSTALL === 'true'` should be sufficient and correct.

2024-11-15 13:55 UTC, odockal commented on tests/playwright/src/spec/minikube-extension.spec.ts
> +    await waitForPodmanMachineStartup(page);
do we need podman machine at this point?

2024-11-15 13:56 UTC, odockal commented
Otherwise it is good. I have tested it locally.

2024-11-18 09:36 UTC, odockal commented on tests/playwright/src/spec/minikube-extension.spec.ts
> +import {
please just 2024.

2024-11-18 09:36 UTC, odockal approved these changes
Only one copyright update, otherwise LGTM.

2024-11-18 09:46 UTC, merged