chore(test): minikube binary installation e2e test
podman-desktop/extension-minikube pull request #228
Opened 2024-11-18 13:26 UTC by amisskii

What issues does this PR fix or reference?

https://github.com/podman-desktop/extension-minikube/issues/138
How to test this PR?

    Clone the podman-desktop repo
    cd to podman-desktop folder
    Execute pnpm install
    Execute pnpm build
    Set environment variable executing: export PODMAN_DESKTOP_ARGS="/path/to/podman-desktop"
    Clone the podman-desktop-extension-minikube repo
    cd to podman-desktop-extension-minikube folder
    Execute pnpm install
    Execute pnpm test:e2e

2024-11-18 13:31 UTC, axel7083 commented
Linter seems unhappy

2024-11-18 13:41 UTC, benoitf approved these changes

2024-11-18 15:01 UTC, odockal requested changes

2024-11-18 15:01 UTC, odockal commented on package.json
> +    "@podman-desktop/tests-playwright": "1.15.0-202411180939-78062c24cd",
This is not correct. We should not be tied to the particular release of npm package. Next is ok. On CI we then add latest release version - aka nightly.

2024-11-19 11:10 UTC, odockal approved these changes

2024-11-19 11:32 UTC, merged