ci: create gha workflow to automate e2e tests
podman-desktop/extension-minikube pull request #235
Opened 2024-11-19 10:12 UTC by amisskii

What issues does this PR fix or reference?

https://github.com/podman-desktop/extension-minikube/issues/139

2024-11-19 10:54 UTC, axel7083 approved these changes

2024-11-19 10:59 UTC, benoitf commented
I want to check the PR before it's being merged, not once it's merged

2024-11-19 11:12 UTC, odockal commented
@benoitf That is different issue: https://github.com/podman-desktop/extension-minikube/issues/140.

2024-11-19 11:16 UTC, odockal requested changes
Overal is quite ok, just some minor changes, consider adding PR check first so we can see the tests in action.

2024-11-19 11:16 UTC, odockal commented on .github/workflows/e2e-main.yaml
> +          path: ./**/tests/**/output/
Missing EOF?

2024-11-19 11:16 UTC, odockal commented on .github/workflows/e2e-main.yaml
> +  schedule:
I think it is better to have trigger event "on: push" into main branch.

2024-11-28 09:58 UTC, odockal requested changes

2024-11-28 09:58 UTC, odockal commented on .github/workflows/e2e-main.yaml
> +          pnpm install --lockfile-only
you are calling `pnpm install` twice, here and in the next step.

2024-12-02 09:07 UTC, odockal approved these changes

2024-12-02 09:08 UTC, merged